### ISSUE TITLE
Develop a HazardParameter Enum

### ISSUE THREAD

**Issue by HenryGeorgist** [USACE/consequences#8]
Back the enum by an int64. We will use byte positions to flag if a hazard is present.  This will be useful when inspecting Hazards at later stages in the compute.
Set the first position as "no hazard"
Set the second postion as "depth" = 2
Set the third position as "velocity" = 4
set the fourth position as "arrival_time" = 8
set the fifth position as "arrival_time_2ft"  = 16

see https://github.com/USACE/go-consequences/blob/main/hazards/interfaces.go  Parameter constant.

**Comment by jackschonherr** [comment]
Is there a specific reason why we want to use an int64 rather than an int (default)?

**Comment by HenryGeorgist** [comment]
great question. since we instructed you to do depth (or in the ticket we instructed depth velocity, arrival time and arrival time 2 ft) then we can actually work with an int. int64 gives us room to add more attributes as a bitflag. switching to an int is fine for the work you are doing.

**Comment by Brennan1994** [comment]
You're also assigning them to powers of two. Is this a bitflag enum? In dotnet wold, we may have to add a [Flags] attribute at the top to convey that. Some documentation and explanation here. 
https://learn.microsoft.com/en-us/dotnet/fundamentals/runtime-libraries/system-flagsattribute
